name: source_gen_test_golden
version: 1.0.5
description: >-
  Test support for the source_gen package.
  Allows to compare the output of a generator with a golden file.
repository: https://github.com/alexeyinkin/dart-source-gen-test-golden

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  analyzer: ^6.4.1
  build: ^2.0.0
  build_test: ^2.0.0
  dart_style: ^2.0.0
  meta: ^1.0.2
  path: ^1.3.2
  source_gen: ^1.0.0
  test: ^1.3.3

dev_dependencies:
  collection: ^1.15.0
  dart_flutter_team_lints: ^1.0.0
